### ISSUE TITLE
Logging when deployed

### ISSUE THREAD

**Issue by keorn** [GREsau/rocket-lamb#1]
Thanks for a great project, I have been using it for a [few simple lambdas](https://gitlab.com/plantingspace/mangrove/-/tree/master/servers). Running into a small issue though.

When running my server locally I am able to get stdout fine, but when deployed the CW logs do not show any of it (just the Lambda system messages). Any ideas on how to address that?

**Comment by GREsau** [comment]
I just deployed a lambda that runs `println!("Hello world!!!!!")` when serving a request, and it does show up in the cloudwatch logs for me:
![image](https://user-images.githubusercontent.com/9611672/74084719-903a9000-4a69-11ea-8b7e-c0b28527f656.png)

How are you writing to stdout - are you using `println!` or something more complex?

**Comment by keorn** [comment]
Indeed, testing `println` works. So looks like Rocket logs and logs from `log` crate do not come out. Setting `RUST_LOG` env variable in Lambda to `rocket,launch,_=debug` does not help.

Looking into it.

**Comment by GREsau** [comment]
I may have figured out what's going on, after reading https://rocket.rs/v0.4/guide/configuration/

When running your server locally, it will be built in debug mode, so Rocket will be operating in the `development` environment. This makes its log level default to `normal`, so INFO and above are logged. But the lambda package is built in release mode, so Rocket will operate in the `production` environment, making its log level `critical`.

So you should be able to restore logging in your lambda by setting the `ROCKET_LOG` env var to `normal` (or `debug`). You could alternatively configure it in a [`Rocket.toml` file](https://rocket.rs/v0.4/guide/configuration/#rockettoml), or set it programmatically using [`custom`](https://api.rocket.rs/v0.4/rocket/struct.Rocket.html#method.custom)/[`Config`](https://api.rocket.rs/v0.4/rocket/struct.Config.html)

Could you try one of those and re-test?

**Comment by keorn** [comment]
Ah, indeed. Thanks a lot `ROCKET_LOG` was needed instead of just `RUST_LOG`. Way easier to monitor now!
