### ISSUE TITLE
Error when invoking locally

### ISSUE THREAD

**Issue by dbanty** [GREsau/rocket-lamb#2]
When running a rocket-lamb application via `sam local start-api` then attempting to call the function via `curl http://127.0.0.1:3000/` I am getting a response of `{"message":"Internal server error"}` with several `Error: Response headers do not contain Lambda-Runtime-Invoked-Function-Arn header` in the logs.

## To Reproduce
1. Clone https://github.com/GREsau/example-rocket-lamb-api
2. Run `docker-compose run --rm build`
3. Run `sam local start-api`

## Other Info
1. I tried this on my own project first and got the same result, then tried out the example assuming something was wrong. Locally I cross-compile to x86_64-unknown-linux-musl from macOS whereas the example uses a containerized build.
2. Platform: macOS 11.1 x86_64 (not ARM)
3. I did not have softprops/lambda-rust locally so it pulled the latest on run
4. Rust version: 1.51.0-nightly (bc39d4d9c 2021-01-15)
5. SAM CLI version: 1.15.0 (installed via Homebrew)

Let me know if there is any other info I can provide that would be useful!

**Comment by GREsau** [comment]
caused by https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/11

**Comment by dbanty** [comment]
Great find! Seems the workaround is to downgrade to aws-sam-cli 1.12.0 for now then. Doing so got my little prototype working, thanks!

**Comment by dbanty** [comment]
I don't think there's really anything to do here, so I'm going to close this. Thanks again!

**Comment by dbanty** [comment]
BTW my fork of rocket_lamb which uses the `lamedh_` crates works fine with the latest SAM CLI 1.18.2. Not sure if that means the issue was fixed in SAM or lamedh, but if my fork is ever merged upstream for Rocket 0.5 support then this will work too!
